### ISSUE TITLE
use Black 22.3.0 or higher

### ISSUE THREAD

**Issue by extreme4all** [piotrpawlaczek/python-black-check#9]
i'm getting the following error: which seems like a version issue
`ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.10/site-packages/click/__init__.py)`
https://stackoverflow.com/a/71674345/4477261

**Comment by piotrpawlaczek** [comment]
This is unlikely as the click version was pinned to `8.0.4`
The incompatibility was between versions black 22.1.0 and Click 8.1.0

I am upgrading to 22.3.0 soon https://github.com/piotrpawlaczek/python-blacken/commit/3300482ee29b6fe01c4c67e1e579a26b3ac17bf5
